### ISSUE TITLE
Error: ENOENT, no such file or directory './output/ulm/data_large.lines'

### ISSUE THREAD

**Issue by nselikoff** [cmichi/gtfs-visualizations#1]
Hi @cmichi, great job on this project! I just followed your directions to clone and set up the code, and when I run `make render gtfs=ulm` I get an error. It seems the code is looking for a data_large.lines file that doesn't exist. I'm not getting any files in the output folders.

````
mkdir -p output/
mkdir -p output/ulm/
time node render.js --verbose --gtfs=ulm
12h32m: Loading GTFS files...
12h32m: GTFS files loaded.

12h32m: Starting to prepare data...
12h32m: Preparing data finished.
12h32m:
Starting to create shape segments array with trips per segment...
12h32m: Segments created.
12h32m: max trips per segment: 1200
12h32m: min trips per segment: 1

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory './output/ulm/data_large.lines'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.truncateSync (fs.js:578:15)
    at createFile (/Volumes/Data/Code/trip/gtfs-visualizations/render.js:250:5)
    at route_types (/Volumes/Data/Code/trip/gtfs-visualizations/render.js:44:2)
    at /Volumes/Data/Code/trip/gtfs-visualizations/parser/loader.js:10:3
    at Object.submit (/Volumes/Data/Code/trip/gtfs-visualizations/parser/barrier-points.js:14:5)
    at /Volumes/Data/Code/trip/gtfs-visualizations/parser/loader.js:78:12
    at /Volumes/Data/Code/trip/gtfs-visualizations/parser/csv-loader.js:40:4
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
        1.56 real         1.48 user         0.09 sys
make: *** [render] Error 8
````

**Comment by cmichi** [comment]
Thanks for the report and the solution! 

It took me a while to add the fix to the code, but I have done so now (7a52beef149b9f3a12b65c352da2261223cdfb7c).
